### ISSUE TITLE
What does the if statement at the top of the class definition in robot.py do?

### ISSUE THREAD

**Issue by Samathy** [502BadGateway/project_3#1]
There is an if statement at the top of the class definition in robot.py. It was uncommented, what does it do and why is it there?

**Comment by danbeglin** [comment]
Its a pyGame thing. Essentially if the object hasn't been initialised before, it loads an image. It doesn't quite make sense, but its needed.

Seems to be a messy work around commonly used by everyone due to a pyGame bug maybe?
