### ISSUE TITLE
Incomplete: Users can place treasures on screen, and it changes value in array

### ISSUE THREAD

**Issue by dannyb648** [502BadGateway/project_3#12]

**Comment by phil-bell** [comment]
what is the name of the array?

**Comment by Samathy** [comment]
__arena is a private variable of the arena class.
an arena class instance is encapsulated within the city class.

The value of a tile of the arena within a city can be retreived by calling the method:

city.area.ret_element_value(int:row, int:col). This will return integers 0, 1, or 2.
