### ISSUE TITLE
Incomplete: Display the actual collectorbot on screen

### ISSUE THREAD

**Issue by dannyb648** [502BadGateway/project_3#17]

**Comment by Samathy** [comment]
Additionally blocked by issue #34

**Comment by Samathy** [comment]
Issue finally resolved in commit 56d97294efd839a36ddd5d64c85f5ab7816742cf

**Comment by danbeglin** [comment]
While the issue probably works on your machine, this is because you've used PIL. Everyone else without it cannot run it.

**Comment by Samathy** [comment]
Fixed in commits bc10279a0e5f635f32ddba616244ad88ed07b9e4, c16eb30cc1aa66b0dcb8768d7be92b5297744260 , b415391f70ff1806a3c0a30f5250855bf241c9b3
