### ISSUE TITLE
Incomplete: Display treasure icons on screen

### ISSUE THREAD

**Issue by dannyb648** [502BadGateway/project_3#19]

**Comment by Samathy** [comment]
A relevent icon needs to be choosen.

**Comment by danbeglin** [comment]
There are now icons in the assets folder which can be scaled to 20x20 if needs be

**Comment by Samathy** [comment]
Thanks.

**Comment by danbeglin** [comment]
Nothing displays on screen, so its not complete. Need to run from main file.

**Comment by Samathy** [comment]
Waiting on resolution of issue #37
