### ISSUE TITLE
Incomplete: Generate all six cities

### ISSUE THREAD

**Issue by dannyb648** [502BadGateway/project_3#23]

**Comment by Samathy** [comment]
THIS ISSUE BLOCKS MANY MORE. WILL FIX ASAP

**Comment by Samathy** [comment]
Why has this been reopened?

**Comment by Samathy** [comment]
staticmap[CITY].png images were wrongly analysed instead of the images without text. Should re-do this.

**Comment by Samathy** [comment]
Should regen only tokyo map
