### ISSUE TITLE
"HEAD" comments seem to be giving errors

### ISSUE THREAD

**Issue by dannyb648** [502BadGateway/project_3#35]
# <<<<<<< HEAD

> > > > > > > d3e12b9ff8e11b8f0f8cd2ef478b77f606c7a781

This code in main.py is causing errors when ran on my machine.

**Comment by Samathy** [comment]
The head tags were caused by your merging. Your job to fix. (Commit cd551651aefc112c2abf1314b58847689aa12571)

The code I added can't run anyway because it requires prerequisite code from Phil. Comment it out if you want, but its there in preparation for Phil's code.

**Comment by danbeglin** [comment]
Didn't realise it was caused by my stuff, assumed it was a linux thing i didn't understand from you.

please be nicer  - I wasn't mean to you.
