### ISSUE TITLE
Would creating a new treasures object to use in the collector bot phase make sense?

### ISSUE THREAD

**Issue by Samathy** [502BadGateway/project_3#37]
We have a treasure class, but its unsuitable for using in the collectorbot phase of the program. Should i create another treasures class for this purpose?

**Comment by danbeglin** [comment]
As long as we can get from your treasure class to mine thats fine. I need the exact same treasures but with points and a 140x140 image aswell.

If that is workable and we can create objects i need from yours, its not an issue
