### ISSUE TITLE
Finding PIL dotted throughout the software

### ISSUE THREAD

**Issue by dannyb648** [502BadGateway/project_3#38]
After going through last nights work, a lot of the files are importing PIL.

We are not using PIL this term, its depreciated, won't install on half the teams machines and we all agreed not to use it

Hopefully this is just because we have pulled work from Project 2? 

Clarification and remove needed.

**Comment by Samathy** [comment]
Fixed in commits bc10279a0e5f635f32ddba616244ad88ed07b9e4, c16eb30cc1aa66b0dcb8768d7be92b5297744260 , b415391f70ff1806a3c0a30f5250855bf241c9b3
