### ISSUE TITLE
City Arena issue, blocking Phils code.

### ISSUE THREAD

**Issue by dannyb648** [502BadGateway/project_3#39]
Line 266: city.arena.ret_element_value(x,y) = treasureNum

( #changes the number in the array from a road to the relevant treasure number the treasures will always be placed in the same order, the order they are in arrayNumberReference.txt)

This line produces a syntax error as seen:

"SyntaxError: can't assign to function call"

This error is blocking Phil from testing any of this code ready for tomorrow.

Can you take a look?

**Comment by danbeglin** [comment]
Also same issue occurs on line 281. (Exact same issue)

**Comment by Samathy** [comment]
Fixed with commit c39ca1557a1f53647093cacca191c91450eb2562
