### ISSUE TITLE
Incomplete: Window displays menu of Cities

### ISSUE THREAD

**Issue by dannyb648** [502BadGateway/project_3#8]
While I've seen this done, it needs to be ran from the main file using the display class.

**Comment by phil-bell** [comment]
done

**Comment by danbeglin** [comment]
Doesn't run from main file, so it isn't complete. If it isn't integrated into the main file and display class, it isn't "complete" If we submitted the project as is, we wouldn't get the marks for selection, as its not in the actual program.

**Comment by danbeglin** [comment]
Essentially, if I run the main.py If I see the map selection, its complete, if not. it isn't.

**Comment by danbeglin** [comment]
I ran the main, and this works. Closing
