### ISSUE TITLE
Incomplete: Picked city initialises city chosen and arena

### ISSUE THREAD

**Issue by dannyb648** [502BadGateway/project_3#9]
When the user picks a city, we need to create in instance of the arena and city class picked, with the array and images etc. 

Phil and Sam

**Comment by Samathy** [comment]
Loose dependancy on issue #23

**Comment by Samathy** [comment]
Fixed in commits  0d91d567db254b81624c32fa5c236bd437004864 and commit e5bbe052518e66435cabb3454fa1b05f41c8b10c.

TODO - Close and exit map select window once city instance is created.

Please not main.py appears to hang once map is choosen. This is not incorrect behaviour.

**Comment by danbeglin** [comment]
SAM DID IT YAY
